### ISSUE TITLE
ggcr: mounting does not retry on authentication failed

### ISSUE THREAD

**Issue by joaopapereira** [google/go-containerregistry#1609]
### Describe the bug

When mounting an image if 401 is returned by the registry ggcr does not try to do the upload of the bits instead.
There is some logic already to try and retry without mounting, but that only happens when ggcr is doing cross-registry mounts. [code in here](https://github.com/google/go-containerregistry/blob/main/pkg/v1/remote/write.go#L292)

### To Reproduce

1. Create 1 image on a repository that needs authentication
2. Without login try to copy that image to a different repository on the same registry (this should try to mount the blob)

### Expected behavior

Our expectation is that this retry would happen also when there was a 401

- Version of module 0.14.0
- Registry used (e.g., GCR, ECR, Quay): Harbor

**Comment by jonjohnsonjr** [comment]
Should be fixed by https://github.com/google/go-containerregistry/pull/1681

**Comment by praveenrewar** [comment]
Hi @jonjohnsonjr! We are still facing this issue. Since both the repositories exists on the same registry, uploading is not retried without mount because of [this](https://github.com/google/go-containerregistry/blob/2472cbbbf289ba63c82649f2b7fd0fc5c9c4845c/pkg/v1/remote/write.go#L223) (`origin != w.repo.RegistryStr()`) condition.

**Comment by jonjohnsonjr** [comment]
Yeah, I believe that's the same issue with https://github.com/google/go-containerregistry/issues/1741

I might just hardcode exclude dockerhub because they keep changing their implementation and breaking this.
